# 87651260 Applications of Geographic Information System

# Python 101 
## Reference : Python ๑๐๑ - วิศวกรรมคอมพิวเตอร์ จุฬาลงกรณ์มหาวิทยาลัย
## Attawut Nardkulpat, Reseach Officer, Burapha University
### attawut@buu.ac.th
### 01/08/2020

In [1]:
!python --version

Python 3.7.6


# Data Type, Variable and Expression

## Data Type

In [5]:
a = b = c = 0.0
print(a)
print(b)
print(c)

0.0
0.0
0.0


In [14]:
a = 3+97//2**3%8 #a มีค่ำ 3+97//8%8 = 3+12%8 = 3+4 = 7
print(a)

7


In [15]:
a = 12//3/2+2**3**2 #a มีค่ำ 12//3/2+2**9 = 12//3/2+512 = 4/2+512 = 2.0+512 = 514.0
print(a)

514.0


In [17]:
a += 2 #a = a + 2
print(a)

518.0


In [20]:
import math
#math.pi, math.e, math.sin(x), math.cos(x), math.sqrt(x), math.log(x,b), ...
a = math.pi
print(a)

3.141592653589793


In [21]:
a = math.sin(45)
print(a)

0.8509035245341184


In [22]:
math.sqrt(4)

2.0

In [23]:
math.log(4,2)

2.0

In [24]:
'12'+'23'

'1223'

In [25]:
int('12')

12

In [26]:
float('1.2')

1.2

In [27]:
str(12//2)

'6'

## input

In [30]:
a = input()
print(a)

20


In [32]:
a = input().strip()
print(a)

abcdefg


In [34]:
a = int(input())
a = float(input())

# Selection ( if-elif-else )

In [40]:
if day == "Sunday":
    print("Sleep in")
elif day == "Saturday":
    print("Do chores")
else:
    print("Go to work")

Do chores


Today is Sunday
   Sleep in
Today is Monday
   Go to work
Today is Tuesday
   Go to work
Today is Wednesday
   Go to work
Today is Thursday
   Go to work
Today is Friday
   Go to work
Today is Saturday
   Do chores


# Repetition ( while, for )

In [43]:
x = 0

while x < 10:
    print('x is currently: ',x)
    print(' x is still less than 10, adding 1 to x')
    x+=1

x is currently:  0
 x is still less than 10, adding 1 to x
x is currently:  1
 x is still less than 10, adding 1 to x
x is currently:  2
 x is still less than 10, adding 1 to x
x is currently:  3
 x is still less than 10, adding 1 to x
x is currently:  4
 x is still less than 10, adding 1 to x
x is currently:  5
 x is still less than 10, adding 1 to x
x is currently:  6
 x is still less than 10, adding 1 to x
x is currently:  7
 x is still less than 10, adding 1 to x
x is currently:  8
 x is still less than 10, adding 1 to x
x is currently:  9
 x is still less than 10, adding 1 to x


In [37]:
days_of_the_week = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]

for day in days_of_the_week:
    print(day)

Sunday
Monday
Tuesday
Wednesday
Thursday
Friday
Saturday


In [38]:
for day in days_of_the_week:
    statement = "Today is " + day
    print(statement)

Today is Sunday
Today is Monday
Today is Tuesday
Today is Wednesday
Today is Thursday
Today is Friday
Today is Saturday


In [39]:
for i in range(20):
    print("The square of {} is {}.".format(i, i*i))

The square of 0 is 0.
The square of 1 is 1.
The square of 2 is 4.
The square of 3 is 9.
The square of 4 is 16.
The square of 5 is 25.
The square of 6 is 36.
The square of 7 is 49.
The square of 8 is 64.
The square of 9 is 81.
The square of 10 is 100.
The square of 11 is 121.
The square of 12 is 144.
The square of 13 is 169.
The square of 14 is 196.
The square of 15 is 225.
The square of 16 is 256.
The square of 17 is 289.
The square of 18 is 324.
The square of 19 is 361.


## Mix : for , if - elif - else

In [ ]:
for day in days_of_the_week:
    statement = "Today is " + day
    print(statement)
    if day == "Sunday":
        print("   Sleep in")
    elif day == "Saturday":
        print("   Do chores")
    else:
        print("   Go to work")

## ข้อสังเกต


In [45]:
for k in range(1, 4) :
    print(k)
    k += 2
    print(k)

1
3
2
4
3
5


In [46]:
k = 1
while k < 4 :
    print(k)
    k += 2
    print(k)

1
3
3
5


In [44]:
# DO NOT RUN THIS CODE!!!! 
#while True:
#    print 'Uh Oh infinite Loop!'

# String

In [71]:
# Use quotation marks for defining string
"Michael Jackson"

# Use single quotation marks for defining string
'Michael Jackson'

# Digitals and spaces in string
'1 2 3 4 5 6 '

# Print the string
print("hello!")

# Assign string to variable
Name = "Michael Jackson"
Name

hello!


'Michael Jackson'

## Indexing

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsIndex.png" width="600" align="center" />


In [74]:
print(Name[0])
print(Name[6])
print(Name[13])

M
l
o


## Negative Indexing

In [75]:
print(Name[-1])
print(Name[-15])

n
M


In [76]:
len("Michael Jackson")

15

## Slicing

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsSlice.png" width="600" align="center" />

In [78]:
print(Name[0:4])
print(Name[8:12])

Mich
Jack


## Stride

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsStride.png" width="600" align="center" />

In [79]:
# Get every second element. The elments on index 1, 3, 5 ...
Name[1::2]

'ihe ako'

In [80]:
# Get every second element in the range from index 0 to index 4
Name[0:5:2]

'Mca'

## Concatenate Strings

In [81]:
Statement = Name + "is the best"
Statement

'Michael Jacksonis the best'

In [82]:
3 * "Michael Jackson"

'Michael JacksonMichael JacksonMichael Jackson'

In [83]:
Name = "Michael Jackson"
Name = Name + " is the best"
Name

'Michael Jackson is the best'

## Escape Sequences

In [85]:
# New line escape sequence
print(" Michael Jackson \n is the best" )

Michael Jackson 
 is the best
 Michael Jackson 	 is the best


In [86]:
# Tab escape sequence
print(" Michael Jackson \t is the best" )

Michael Jackson 	 is the best


In [87]:
# Include back slash in string
print(" Michael Jackson \\ is the best" )

Michael Jackson \ is the best


In [88]:
# r will tell python that string will be display as raw string
print(r" Michael Jackson \ is the best" )

Michael Jackson \ is the best


## String Operations

In [89]:
# Convert all the characters in string to upper case
A = "Thriller is the sixth studio album"
print("before upper:", A)
B = A.upper()
print("After upper:", B)

before upper: Thriller is the sixth studio album
After upper: THRILLER IS THE SIXTH STUDIO ALBUM


In [90]:
# Replace the old substring with the new target substring is the segment has been found in the string

A = "Michael Jackson is the best"
B = A.replace('Michael', 'Janet')
B

'Janet Jackson is the best'

<img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/PY0101EN/Chapter%201/Images/StringsFind.png" width="600" align="center" />

In [91]:
# Find the substring in the string. Only the index of the first elment of substring in string will be the output
Name = "Michael Jackson"
Name.find('el')

5

In [92]:
# Find the substring in the string.
Name.find('Jack')

8

In [96]:
# If cannot find the substring in the string
Name.find('iasdasdc')

-1

# List

In [49]:
x = []
y = list()
x == y

True

In [2]:
a = [1,2,3]
b = [1,2,3]
c = b
d = list(b)

In [3]:
len(a)

3

In [53]:
x = list(a)
print(x)
x = list('abcde')
print(x)
x = list(range(1,10,2))
print(x)

[1, 2, 3]
['a', 'b', 'c', 'd', 'e']
[1, 3, 5, 7, 9]


In [59]:
type(x)

list

In [61]:
x = 2*([1,2,3] + [3,4,5])
print(x)

[1, 2, 3, 3, 4, 5, 1, 2, 3, 3, 4, 5]


In [63]:
x.append(1)
print(x)

[1, 2, 3, 3, 4, 5, 1, 2, 3, 3, 4, 5, 1, 1]


In [64]:
x.insert(0, 0) #x.insert(i, e)
print(x)

[0, 1, 2, 3, 3, 4, 5, 1, 2, 3, 3, 4, 5, 1, 1]


In [73]:
x.pop(0)
print(x)

[3, 3, 4, 5, 1, 1]


In [75]:
x.sort()
print(x)

[1, 1, 3, 3, 4, 5]


In [76]:
sorted(x)

[1, 1, 3, 3, 4, 5]

In [80]:
print(sum(x))
print(max(x))
print(min(x))

17
5
1


In [102]:
my_list = ['A string',23,100.232,'o']
print(my_list)

['A string', 23, 100.232, 'o']


In [103]:
len(my_list)

4

# Nested List

In [4]:
x = []
x.append( 1 ) # [1]
x.append( [2,3] ) # [1,[2,3]]
x.append( [4,5,6] ) # [1,[2,3],[4,5,6]]
x.append( [[7,8]] ) # [1,[2,3],[4,5,6],[[7,8]]]
x.append( [] ) # [1,[2,3],[4,5,6],[[7,8]],[]]

In [5]:
x

[1, [2, 3], [4, 5, 6], [[7, 8]], []]

# List Comprehension

In [7]:
lst = [x for x in 'word']
print(lst)

['w', 'o', 'r', 'd']


In [8]:
lst = [x**2 for x in range(0,11)]
print(lst)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [9]:
lst = [x for x in range(11) if x % 2 == 0]
print(lst)

[0, 2, 4, 6, 8, 10]


In [12]:
lst = [ x**2 for x in [x**2 for x in range(11)]]
print(lst)

[0, 1, 16, 81, 256, 625, 1296, 2401, 4096, 6561, 10000]


# Tuple, Dictionary and Set

## List&Tuple

In [13]:
my_list = [1, 2.5, 3, 'A'] #list
my_tuple = (1, 2.5, 3, 'A') #tuple

In [15]:
print(type(my_list))
print(type(my_tuple))

<class 'list'>
<class 'tuple'>


In [19]:
my_tuple_2 = (1,)
not_a_tuple = (1)

In [20]:
print(type(my_tuple_2))
print(type(not_a_tuple))

<class 'tuple'>
<class 'int'>


In [16]:
t1 = tuple('abc')
t2 = tuple([1, 2, 3])

In [18]:
print(t1)
print(t2)

('a', 'b', 'c')
(1, 2, 3)


## Dictionary

In [23]:
dict1 = {}
dict2 = dict()

In [24]:
print(type(dict1))
print(type(dict2))

<class 'dict'>
<class 'dict'>


In [27]:
D = {'Name':'Sarah'}

In [28]:
print(D['Name'])

Sarah


In [29]:
D['Age'] = 20

In [30]:
D['Name'] = 'Somsri'

In [32]:
print(D['Name'])
print(D['Age'])

Somsri
20


## Set

In [35]:
set_1 = set()
set_2 = {1, 2, 3}

In [40]:
print(type(set_1))
print(set_2)

<class 'set'>
{1, 2, 3}


In [37]:
set_3 = set('Hello')
set_4 = set(['oh', 'no']) 
set_5 = set(set_2)
set_6 = set({1:2, 3:4})

In [41]:
print(set_3)
print(set_4)
print(set_5)
print(set_6)

{'e', 'H', 'o', 'l'}
{'no', 'oh'}
{1, 2, 3}
{1, 3}


# Function and Recursion

In [42]:
print(median(3,1,2))

NameError: name 'median' is not defined

In [43]:
def median(x,y,z):
    return (x+y+z)-min(x,y,z)-max(x,y,z)

In [44]:
median(1,2,3)

2

In [45]:
def average(x,y):
    return (x+y)/2

In [46]:
average(10,20)

15.0

In [47]:
def factorial(n):
    if n < 2: return 1
    return n * factorial(n-1)

In [48]:
factorial(5)

120

# NumPy

In [49]:
import numpy as np

## Numpy Basics

In [51]:
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])  # 1*15 vector

print(array.shape) # Array dimensions

a = array.reshape(3,5) # Reshape, but don’t change data
print("shape: ",a.shape)
print("dimension: ", a.ndim) # Number of array dimensions
print("data type: ",a.dtype.name) # Data type of array elements
print("size: ",a.size) # Number of array elements
print("type: ",type(a))

array1 = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,5]])
zeros = np.zeros((3,4)) # Create an array of zeros

zeros[0,0] = 5
print(zeros)

np.ones((3,4)) # Create an array of ones

np.empty((2,3)) # Create an empty array

a = np.arange(10,50,5) # Create an array of evenly   spaced values (step value)
print(a)

a = np.linspace(10,50,20) # Create an array of evenly   spaced values (number of samples)
print(a)

print("--------------------------------------")
# Asking for help
np.info(np.ndarray.dtype)

(15,)
shape:  (3, 5)
dimension:  2
data type:  int32
size:  15
type:  <class 'numpy.ndarray'>
[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20 25 30 35 40 45]
[10.         12.10526316 14.21052632 16.31578947 18.42105263 20.52631579
 22.63157895 24.73684211 26.84210526 28.94736842 31.05263158 33.15789474
 35.26315789 37.36842105 39.47368421 41.57894737 43.68421053 45.78947368
 47.89473684 50.        ]
--------------------------------------
Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Numpy Basic Operations

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

# Arithmetic Operations

print(a+b) # Addition
print(a-b) # Subtraction
print(np.sin(a)) # Print sines of an array
print(np.sqrt(a)) # Square root
print(np.square(a)) # a**2
print(np.add(a,a)) # Addition

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

# element wise prodcut
print(a*b)

# matrix prodcut
a.dot(b.T)

print(np.exp(a)) # Exponentiation
print(np.log(a)) # Element-wise natural logarithm 
a = np.random.random((5,5))

print("---------------------------------------------")
# Aggregate Functions

print(a.sum()) # Array-wise sum
print(a.max()) # Maximum value of an array row
print(a.min()) # Array-wise minimum value 
print(a.sum(axis=0)) # Sum of an array row
print(a.sum(axis=1)) # Sum of an array column
print(a.mean()) # Mean
print(np.std(b)) # Standard deviation
print("---------------------------------------------")

[5 7 9]
[-3 -3 -3]
[0.84147098 0.90929743 0.14112001]
[1.         1.41421356 1.73205081]
[1 4 9]
[2 4 6]
[[ 1  4  9]
 [16 25 36]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
---------------------------------------------
14.707992318196398
0.9699281352471656
0.014812423422647325
[2.67850054 2.77971317 3.97068216 1.91989051 3.35920595]
[3.15789319 2.86861768 3.23352442 2.1280112  3.31994583]
0.5883196927278559
1.707825127659933
---------------------------------------------


## Indexing and Slicing

In [53]:
array = np.array([1,2,3,4,5,6,7])   #  vector dimension = 1
print("Array: ",array)
print(array[0]) # Select the element at the zero index

print(array[0:4]) # Select items at index 0, 1, 2 and 3

reverse_array = array[::-1] # Reversed array
print(reverse_array)

print("--------------------------------------------------")

array1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array 1: ", array1)
print(array1[1,1]) # Select items at row 1 in column 1
print(array1[:,1])
print(array1[1,1:4]) 
print(array1[-1,:])
print(array1[:,-1])

Array:  [1 2 3 4 5 6 7]
1
[1 2 3 4]
[7 6 5 4 3 2 1]
--------------------------------------------------
Array 1:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[2 7]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


## Shape Manipulation

In [55]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n", array)

# Transposing Array
print("Transpose of array :\n", array.T) 

# Changing Array Shape
a = array.ravel() # Flatten the array
array2 = a.reshape(3,3) # Reshape, but don’t change data

# Stacking Arrays
array3 = np.array([[1,2],[3,4]])
array4 = np.array([[-1,-2],[-3,-4]])

# Veritical Combining
array5 = np.vstack((array3,array4))
print("Veritical Combining: \n",array5)
# Horizontal Combining
array6 = np.hstack((array3,array4))
print("Horizontal Combining: \n",array6)

# Different Combining Technique
np.concatenate((array3,array4),axis=0) # Veritical Combining
np.concatenate((array3,array4),axis=1) # Horizontal Combining

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of array :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Veritical Combining: 
 [[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]]
Horizontal Combining: 
 [[ 1  2 -1 -2]
 [ 3  4 -3 -4]]


array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4]])

## Convert and Copy Array

In [56]:
# Convert

liste = [1,2,3,4]   # list

array = np.array(liste) # np.array

liste2 = list(array)

a = np.array([1,2,3])

# Copy Array: These operations are incorrect. Because when you change the contents of one array, the other arrays will be affected.
b = a 
b[0] = 5
c = a 

# Copy Array: These operations are correct. 
d =  np.array([1,2,3])
e = d.copy()
f = d.copy()

# Class

In [57]:
class Book:
    def __init__(self, title, price, keywords):
        self.title = title; self.price = price; self.keywords = set(keywords)

    def __lt__(self, rhs):
        if self.price != rhs.price: return self.price < rhs.price
        else: return self.title < rhs.title

    def __str__(self):
        return self.title + ' ($' + str(self.price) + ')'

    def update_price(self, new_price):
        self.price = new_price

    def get_common_keywords(self, other):
        return self.keywords & other.keywords

In [58]:
b1 = Book('Python', 99, ['code','computer']) # using __init__
b2 = Book('Calculus', 199, ['maths'])
b3 = Book('Physics', 99, ['science','maths'])
b1.update_price(199)


{'maths'}
Python ($199)
Physics ($99) , Calculus ($199) , Python ($199)


In [59]:
print(Book.get_common_keywords(b2,b3)) # {'maths'}

{'maths'}


In [60]:
if b3 < b2: print(b1) # using __lt__ & __str__

Python ($199)


In [63]:
books = [b1,b2,b3]
print(books)

[<__main__.Book object at 0x00000236E8281E48>, <__main__.Book object at 0x00000236E8281D08>, <__main__.Book object at 0x00000236E8281F48>]


In [64]:
books.sort() # using __lt__

In [65]:
print(books[0],',',books[1],',',books[2]) # using __str__
# 'Physics ($99) , Calculus ($199) , Python ($199)

Physics ($99) , Calculus ($199) , Python ($199)
