# Element-wise

In [1]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# [[ 1  2] + [[ 5  6] =  [[ 6  8]
#   [3 4]]    [ 7  8]]    [10 12]]
print(x + y)

# [[-4 -4]
#  [-4 -4]]
print(x - y)

# [[ 5 12]
#  [21 32]]
print(x * y)

# ตัวอย่างการหาร เมื่อเลขไม่ลงตัว สมาชิกใน array จะเปลี่ยนเป็นจำนวนจริงโดยอัตโนมัติเหมือนกรณีการหารตัวเลข
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [2]:
# ยกกำลัง
print(x ** 2)

# ถอดรากที่สองมีสองวิธีคือเรียกฟังก์ชั่นของ numpy หรือ ยกกำลังด้วย 1/2
print(np.sqrt(x))
print(x ** (1/2))

[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


# Broadcasting

In [8]:
import numpy as np
W = np.array([[1,2,3],[4,5,6],[7,8,9]]) #สมมติเรามีเมตริกซ์ขนาด 3x3
print(W,'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [6]:
x = np.array([1,0,1])
print(x,'\n')

[1 0 1] 



In [10]:
y = x.reshape(3,1) # สร้างเวกเตอร์แนวตั้ง หรือคอลัมภ์เวกเตอร์
z = x.reshape(1,3) # สร้างเวกเตอร์แนวนอน
print(y,'\n')
print(z)

[[1]
 [0]
 [1]] 

[[1 0 1]]


In [11]:
print('Broadcasting addition with respect to the column vector : ')
print(W+y,'\n') # บวกทุกคอลัมภ์ของเมตริกซ์ด้วยเวกเตอร์แนวตั้ง

Broadcasting addition with respect to the column vector : 
[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]] 



In [12]:
print('Broadcasting addition with respect to the row vector : ')
print(W+z,'\n') # บวกทุกแถวของเมตริกซ์ด้วยเวกเตอร์แนวนอน

Broadcasting addition with respect to the row vector : 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]] 



In [13]:
# จริงๆ แล้วการคูณเมตริกซ์ด้วยค่าคงที่ก็คือ Broadcasting ชนิดหนึ่ง 
print('Broadcasting constant multiplication example : ')
print(W*2)

Broadcasting constant multiplication example : 
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
